# Generated by Django 5.0.2 on 2024-02-21 20:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=255, unique=True)),
                ('encryptedPw', models.CharField(max_length=255)),
                ('user_type', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='GradData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('gradDate', models.DateField()),
                ('prevJob', models.CharField(max_length=255)),
                ('mentorType', models.CharField(max_length=255)),
                ('mentorText', models.TextField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mentormatch.currentuser')),
            ],
        ),
        migrations.CreateModel(
            name='MentorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('gradDate', models.DateField()),
                ('prevJob', models.CharField(max_length=255)),
                ('currentJob', models.CharField(max_length=255)),
                ('mentorType', models.CharField(max_length=255)),
                ('gradText', models.TextField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mentormatch.currentuser')),
            ],
        ),
    ]
