# Generated by Django 5.0.2 on 2024-02-15 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GradData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gradName', models.CharField(max_length=255)),
                ('gradDate', models.DateField()),
                ('prevJob', models.CharField(max_length=255)),
                ('mentorText', models.TextField()),
            ],
        ),
    ]
