# Generated by Django 5.0.2 on 2024-02-22 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mentormatch', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='currentuser',
            old_name='encryptedPw',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='currentuser',
            old_name='user_type',
            new_name='userType',
        ),
    ]
