# Generated by Django 5.0.2 on 2024-02-15 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentormatch', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mentorName', models.CharField(max_length=255)),
                ('gradDate', models.DateField()),
                ('prevJob', models.CharField(max_length=255)),
                ('currentJob', models.CharField(max_length=255)),
                ('mentorType', models.CharField(max_length=255)),
                ('gradText', models.TextField()),
            ],
        ),
    ]
