# Generated by Django 5.0.2 on 2024-02-20 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mentormatch', '0004_graddata_mentortype'),
    ]

    operations = [
        migrations.RenameField(
            model_name='graddata',
            old_name='gradName',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='mentordata',
            old_name='mentorName',
            new_name='name',
        ),
    ]
